### ISSUE TITLE
google-chrome works

### ISSUE THREAD

**Issue by lounqe** [6c37/crux-ports-orphaned#1]
Hi ,I modified Pkgfile and got google-chrome-stable working

> 

name=google-chrome
version=stable
release=1
source=(https://dl.google.com/linux/direct/google-chrome/${name}-${version}_current_amd64.deb)

build() {
	bsdcpio -i < $SRC/${name}-${version}_current_amd64.deb
	bsdtar -xpf $SRC/data.tar.xz -C $PKG

        rm -r $PKG/usr/share/doc

	for i in 16 22 24 32 48 64 128 256; do
		install -Dm644 "$PKG"/opt/google/chrome/product_logo_${i}.png \
		"$PKG"/usr/share/icons/hicolor/${i}x${i}/apps/google-chrome.png
	done

	gzip "$PKG"/usr/share/man/man1/google-chrome.1

	rm -r "$PKG"/etc/cron.daily/ "$PKG"/opt/google/chrome/cron/
	rm "$PKG"/opt/google/chrome/product_logo_*.png
}

>

**Comment by rtlanceroad** [comment]
yeah, you can accordingly modify that pkgfile as your need, or just see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=google-chrome as a reference.

**Comment by wildefyr** [comment]
See: https://fyrious.ninja/ports/google-chrome/ for reference too, should still work, but been awhile since I've been on crux

**Comment by rtlanceroad** [comment]
Since it's not an issue anymore, i close it.
